### ISSUE TITLE
Error Step 4 

### ISSUE THREAD

**Issue by HENRIQUELOBO** [wouterdeberg/laravel-elastic-email#5]
Erro in MailManager - Unsupported mail transport 

Transport writing error.

'mailers' => [
    ...
    'elastic_email' => [
        'transport' => 'elasticemail',
        'key' => env('ELASTIC_KEY')
    ],  
    ...
],

I typed elastic_email and it stopped the error

**Comment by AvivoB** [comment]
I have the same error: Unsupported mail transport
![image](https://user-images.githubusercontent.com/45241291/198287722-78d14917-6be7-4053-909b-d15be12bbcd4.png)

**Comment by wouterdeberg** [comment]
By changing the transport of mailer elastic_email from `elasticemail` to `elastic_email`. The mailer should work again.
See: https://github.com/wouterdeberg/laravel-elastic-email/commit/80348c4167f314a8e3627c23b9b99bb83150067e
