### ISSUE TITLE
after config but return  Unsupported mail transport [elasticemail].

### ISSUE THREAD

**Issue by vahidalvandi** [wouterdeberg/laravel-elastic-email#7]
Unsupported mail transport [elasticemail].

laravel 9

**Comment by MayDay22** [comment]
Same for me!

**Comment by jonesheckler** [comment]
Same for me! 
Did you find any way to fix it?

**Comment by wouterdeberg** [comment]
By changing the transport of mailer elastic_email from `elasticemail` to `elastic_email`. The mailer should work again.
See: https://github.com/wouterdeberg/laravel-elastic-email/commit/80348c4167f314a8e3627c23b9b99bb83150067e
